config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles

  root 'breweries#index'

  resources :memberships do
    post 'toggle_confirmation', on: :member
  end

  resources :beer_clubs

  resources :users

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :ratings, only: [:index, :new, :create, :destroy]

  resources :sessions, only: [:new, :create]

  resources :places, only: [:index, :show]

  post 'places', to: 'places#search'

  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'

  get 'signin', to: 'sessions#new'

  delete 'signout', to: 'sessions#destroy'
  #get 'signout', to: 'sessions#destroy'

  get 'beerlist', to: 'beers#list'
  get 'ngbeerlist', to: 'beers#nglist'
  get 'brewerylist', to: 'breweries#list'
end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  validates_presence_of :city
  validates :founded, numericality: { less_than_or_equal_to: ->(_) { Time.now.year} }
  validates :name, uniqueness: true, length: { minimum: 3, maximum: 30 }

  def member?(user)
    users.include? user and memberships.find_by(user_id:user.id).confirmed
  end

  def to_s
    return "Club #{name} of #{city}"
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_member, only: [:edit, :delete]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
    @confirmed = Membership.where(confirmed:true, beer_club_id:@beer_club.id)
    @unconfirmed = Membership.where(confirmed:[nil,false], beer_club_id:@beer_club.id)
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        @beer_club.memberships.create user_id:current_user.id, confirmed:true
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer_club }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    update_item(@beer_club, beer_club_params, "Beer Club")
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    destroy_item(@beer_club, beer_clubs_url)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end

    def ensure_that_member
          redirect_to :back, notice:'only members are allowed' unless @beer_club.member?(current_user)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/beer_clubs/_list.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
  <h2 class="panel-title"><%= title %></h2>
  </div>
  <div class="panel-body">
    <ul class="list-group">
      <% members.each do |member| %>
        <li class="list-group-item">
          <%= link_to member.user.username, member.user %>
          <% if confirm %>
            <%= link_to "Confirm", toggle_confirmation_membership_path(member.id), method: :post, class:"btn btn-primary" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer club</h1>

<%= render 'form' %>

app/views/beer_clubs/index.html.erb
<h1>Beer clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club_path(beer_club.id) %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('Create a New Beer club', new_beer_club_path, class:"btn btn-primary") unless current_user.nil? %>

app/views/beer_clubs/new.html.erb
<h1>New Beer club</h1>

<%= render 'form' %>

app/views/beer_clubs/show.html.erb
<h1><%= @beer_club.name %></h1>
<p>
  Founded <%= @beer_club.founded %>,
  is located at <%= @beer_club.city %>
</p>

<%= render 'list', members: @confirmed, title:"Members", confirm:false %>

<%= render 'list', members: @unconfirmed, title:"Outstanding applications", confirm:true  %>

<% if current_user %>
<% unless current_user.beer_clubs.include?(@beer_club) %>
  <%= form_for(@membership) do |f| %>
    <%= f.hidden_field :beer_club_id %>
    <%= f.hidden_field :user_id %>
    <%= f.submit value:"join the club", class:"btn btn-primary"%>
  <% end %>
  <% end %>
<% end %>
<br>
<%= edit_and_destroy_buttons(@beer_club) %>